apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
    app.openshift.io/runtime: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - args:
            - --bind_ip_all
          image: quay.io/mohamedf0/mongo@sha256:53c4915c2c13524007a84b472f8c0b0a3c4f889afcb014306b628b2e82d0b658
          name: mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
  volumeClaimTemplates:
    - metadata:
        name: mongodb
        labels:
          app: monogdb
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd
        volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
